server:
  port: 8181
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver #com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3036/guns?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: a123456789
      initial-size: 5
      max-active: 5


mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  mapper-locations: classpath*:**/mapper/*.xml
  type-aliases-package: com.icegan.edu.questioncrawler.entity
