server:
  port: 8181
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: a123456789
      initial-size: 5
      max-active: 5
      db-type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  mapper-locations: classpath:**/mapper/*.xml
  type-aliases-package: com.icegan.edu.questioncrawler.model
