server:
  port: 8383
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: a123456789 #172.27.0.9 eduoscar
      initial-size: 5
      max-active: 5
      db-type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  type-aliases-package: com.icegan.edu.questioncrawler.model
  mapper-locations: classpath*:**/mapper/*Mapper.xml  #写成classpath*:**/mapper/*.xml会把tomcat下的包含mapper路径的xml文件也囊括进来，所以要注意，或者最好给你的xml一个统一的后缀，比如**Mapper.xml

logging:
  config: classpath:log4j2.xml
  level:
    com.icegan.edu.questioncrawler.dao: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
jasypt:
  encryptor:
    password: icegan #加密的密钥